Bump OpenSSL to 3.5.5 (latest LTS) and the target SDK to 24 to match teh global TARGET SDK - #60

diff --git a/openssl-build-target-archs b/openssl-build-target-archs
--- a/openssl-build-target-archs
+++ b/openssl-build-target-archs
@@ -23,12 +23,16 @@ function setupPathsAndExports {
     LIB_PATH="${OPENSSL_BUILD_OUT_PATH}/libs"
     LOG_PATH="${OPENSSL_BUILD_OUT_PATH}/logs"
 
-    # Export ANDROID_NDK_HOME env var
-    export ANDROID_NDK_HOME=$NDK_PATH
-    # Add toolchains bin directory to PATH
-    TOOLCHAIN_PATH="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64"
-    # for some reason it does not need to be exported
-    PATH=$TOOLCHAIN_PATH/bin:$PATH
+    # Required for OpenSSL + new NDK
+    export ANDROID_NDK_HOME="$NDK_PATH"
+    export ANDROID_NDK_ROOT="$NDK_PATH"
+
+    TOOLCHAIN_PATH="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin"
+
+    export PATH="$TOOLCHAIN_PATH:$PATH"
+
+    # Android API (needed by OpenSSL)
+    export ANDROID_API="${OPENSSL_TARGET_NDK_LEVEL}"
 }
 
 function clearBuildDirectory {
@@ -40,28 +44,42 @@ function clearBuildDirectory {
 function clearTmpDirectory {
     rm -rf "$OPENSSL_TMP_FOLDER"
     mkdir -p "$OPENSSL_TMP_FOLDER"
-    cp -r ${OPENSSL_SRC_PATH}/* ${OPENSSL_TMP_FOLDER}
+    cp -r "${OPENSSL_SRC_PATH}"/* "${OPENSSL_TMP_FOLDER}"
 }
 
 function getArchitecture {
     OPENSSL_TARGET_ABI=$1
-    if [ "$OPENSSL_TARGET_ABI" == "armeabi-v7a" ]
-    then
-        ARCHITECTURE="android-arm"
-    elif [ "$OPENSSL_TARGET_ABI" == "arm64-v8a" ]
-    then
-        ARCHITECTURE="android-arm64"
-    elif [ "$OPENSSL_TARGET_ABI" == "x86" ]
-    then
-        # Use "no-asm" arg as specified in Merge Request #28 --- Use Only for x86 ARCH
-        ARCHITECTURE="android-x86 no-asm"
-    elif [ "$OPENSSL_TARGET_ABI" == "x86_64" ]
-    then
-        ARCHITECTURE="android-x86_64"
-    else
-        echo "Unsupported target ABI: $OPENSSL_TARGET_ABI"
-        exit 1
-    fi
+
+    case "$OPENSSL_TARGET_ABI" in
+
+        armeabi-v7a)
+            ARCHITECTURE="android-arm"
+            export CC="armv7a-linux-androideabi${ANDROID_API}-clang"
+            ;;
+
+        arm64-v8a)
+            ARCHITECTURE="android-arm64"
+            export CC="aarch64-linux-android${ANDROID_API}-clang"
+            ;;
+
+        x86)
+            ARCHITECTURE="android-x86 no-asm"
+            export CC="i686-linux-android${ANDROID_API}-clang"
+            ;;
+
+        x86_64)
+            ARCHITECTURE="android-x86_64"
+            export CC="x86_64-linux-android${ANDROID_API}-clang"
+            ;;
+
+        *)
+            echo "Unsupported ABI: $OPENSSL_TARGET_ABI"
+            exit 1
+            ;;
+    esac
+
+    export AR="llvm-ar"
+    export RANLIB="llvm-ranlib"
 }
 
 
@@ -76,7 +94,8 @@ setupPathsAndExports
 # Clear and recreate the build output directory
 clearBuildDirectory
 # Set clang compiler, instead of gcc by default
-CC=clang
+# No longer required with newer NDK versions, which use clang by default, but leaving it here for older NDK compatibility
+# CC=clang
 
 
 ##############################################################################
@@ -86,7 +105,9 @@ CC=clang
 # Build OpenSSL for each ARCH specified in config.conf
 for arch in "${TARGET_ARCHS[@]}"
 do
+    echo "======================================"
     echo "Configuring OpenSSL for target arch $arch ..."
+    echo "======================================"
 
     # Clear the tmp source directory
     clearTmpDirectory
@@ -97,33 +118,42 @@ do
 
     # Set the target architecture
     # Can be android-arm, android-arm64, android-x86 etc
-    ARCHITECTURE="android-arm"
     getArchitecture $arch
 
+    echo "Using:"
+    echo "  ARCH=$ARCHITECTURE"
+    echo "  CC=$CC"
+
     # Create Makefile
-    ./Configure $ARCHITECTURE -D__ANDROID_API__=${OPENSSL_TARGET_NDK_LEVEL} >> "${LOG_PATH}/${arch}.log" 2>&1
+    ./Configure $ARCHITECTURE -D__ANDROID_API__="$ANDROID_API" >> "${LOG_PATH}/${arch}.log" 2>&1
 
     # Build Openssl
     echo "Building OpenSSL Library for Android arch $arch"
-    make >> "${LOG_PATH}/${arch}.log" 2>&1
-    mkdir -p $OPENSSL_OUTPUT_PATH
-    OUTPUT_LIB=$OPENSSL_OUTPUT_PATH/lib
-    mkdir -p $OUTPUT_LIB
-    OUTPUT_INCLUDE=${OPENSSL_OUTPUT_PATH}/include
-    mkdir -p $OUTPUT_INCLUDE
-    cp -RL include/openssl $OUTPUT_INCLUDE
+    make clean >> "${LOG_PATH}/${arch}.log" 2>&1
+    make -j$(nproc) >> "${LOG_PATH}/${arch}.log" 2>&1
 
-    # Copy libs to final destination folder
-    cp libssl.a $OUTPUT_LIB
-    cp libcrypto.a $OUTPUT_LIB
-    # Uncomment if you want .so libs (pjsip only needs the static libs)
-    # cp libssl.so $OUTPUT_LIB
-    # cp libcrypto.so $OUTPUT_LIB
-    echo "Build completed! Check output libraries in ${OPENSSL_OUTPUT_PATH}"
+    # Output folders
+    mkdir -p "$OPENSSL_OUTPUT_PATH/lib"
+    mkdir -p "$OPENSSL_OUTPUT_PATH/include"
+
+    # Copy Headers
+    cp -RL include/openssl "$OPENSSL_OUTPUT_PATH/include"
+
+    # Copy Static libs
+    cp libssl.a "$OPENSSL_OUTPUT_PATH/lib"
+    cp libcrypto.a "$OPENSSL_OUTPUT_PATH/lib"
+
+    echo "Build completed for $arch"
 done
 
-# Remove tmp folder
-rm -rf ${OPENSSL_TMP_FOLDER}
-echo "Finished building OpenSSL! Check output folder: ${OPENSSL_BUILD_OUT_PATH}"
 
-set +e
+##############################################################################
+############################### CLEANUP ######################################
+##############################################################################
+
+rm -rf "$OPENSSL_TMP_FOLDER"
+
+echo "======================================"
+echo "Finished building OpenSSL!"
+echo "Output: $OPENSSL_BUILD_OUT_PATH"
+echo "======================================"
